#!/usr/bin/env python3
"""Self-verify — the clone RED-TEAMS its own output before it acts.

Phase 5 faculty. decision_modeling asks "would Operator approve?"; this asks the harder,
frontier-move question BEFORE any mutating/outward action fires: "what would make this
WRONG, and did I check?" The goal is confidently-right, not confidently-wrong.

verify(action) -> {safe, verdict, refutations, checks}

Bounded adversarial self-check, deterministic-first (a model is a last resort, opt-in):
  (a) REFUTE   — try to prove the action wrong (broadcast/spray shape, cross-lane leak).
  (b) OUTCOME  — the Blake lesson: a mutation that doesn't actually change state (a perm
                 grant the target already has, a grant to zero members, before==after) is a
                 NO-OP dressed as a win. Caught here, via a structured mutation signal or an
                 injected outcome_fn that re-checks reality.
  (c) DOCTRINE — gate the action through decision_modeling.score; a REJECT is a refutation.
  (d) RAILS    — lane firewall, send-fence (only Operator sends), no AI/stack trace on SF.

Deterministic checks run first and are total. A single cheap local-model refutation pass is
consulted ONLY for a genuine judgment call (nothing deterministic fired, no clear read) and
ONLY when the caller injects ctx['model_fn'] — off by default, smoke never touches it. This
mirrors decision_modeling._llm_judge so there is no hidden network call in an import-only module.

Contract for callers: any mutating or outward action MUST call verify() first and abort on
safe=False. Additive + import-only. __main__ smoke runs fully offline.
"""
from __future__ import annotations

import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable

if __package__ in (None, ""):  # allow `python core/self_verify.py`
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

try:
    from core import decision_modeling as _dm
except Exception:  # fail-soft: doctrine gate degrades, rails still hold
    _dm = None


# ---------------------------------------------------------------------------
# markers (deterministic rails)
# ---------------------------------------------------------------------------
# AI/automation tells that must NEVER appear on a Salesforce/employer surface (HARD RAIL 3).
_AI_TRACE = re.compile(
    r"\b(ai[- ]generated|co[- ]authored[- ]by|as an ai|language model|"
    r"claude|chatgpt|gpt-?\d|anthropic|openai|automated by (?:the )?(?:bot|stack|clone)|"
    r"generated by (?:ai|claude|the))\b",
    re.IGNORECASE,
)
# Hustle/stack identity that must never touch a work surface (HARD RAIL 4, lane firewall).
_STACK_TRACE = re.compile(
    r"\b(claude-stack|hailports|scannerapp|openclaw|the mini|grunt\.py|"
    r"BrandA standard|case_study|geo_blitz)\b",
    re.IGNORECASE,
)
_WORK_SURFACE = {"salesforce", "sfdc", "monday", "outlook", "owa", "zoom", "CompanyA", "employer"}
_SF_SURFACE = {"salesforce", "sfdc"}

# Broadcast / spray shape — a draft aimed at a crowd, not a single hand-raised person.
_BROADCAST_SCOPE = {"group", "broadcast", "mass", "list", "channel", "everyone", "all"}
_BROADCAST_TEXT = re.compile(
    r"\b(broadcast|blast|to all\b|entire (?:list|channel|team|org|audience)|"
    r"everyone|all (?:members|contacts|prospects|users|recipients)|mass (?:email|message|dm))\b",
    re.IGNORECASE,
)


# ---------------------------------------------------------------------------
# action model
# ---------------------------------------------------------------------------
@dataclass
class Action:
    kind: str = "answer"                 # draft | outreach | sf_change | perm_grant | answer | ...
    summary: str = ""                    # one-line description (fed to doctrine + regex)
    text: str = ""                       # body/content, if any
    lane: str = "unknown"                # hustle | work | unknown
    surface: str = ""                    # salesforce | outlook | slack | ...
    target: str = ""                     # recipient / scope description
    scope: str = ""                      # single | group | broadcast | ...
    is_send: bool = False                # True = actually goes outward now (vs stage/draft)
    mutation: dict | None = None         # structured state-change for the outcome/no-op check
    outcome_fn: Callable[[], Any] | None = None  # injected reality re-check -> bool | (bool,str)
    ctx: dict = field(default_factory=dict)

    @property
    def blob(self) -> str:
        return " ".join(x for x in (self.summary, self.text, self.target) if x)


def _normalize(action: Any) -> Action:
    if isinstance(action, Action):
        return action
    if isinstance(action, str):
        return Action(summary=action.strip())
    if isinstance(action, dict):
        d = dict(action)
        fn = d.pop("outcome_fn", None)
        mut = d.pop("mutation", None)
        ctx = d.pop("ctx", None) or d.pop("context", None) or {}
        known = {f for f in Action.__dataclass_fields__ if f not in ("outcome_fn", "mutation", "ctx")}
        kwargs = {k: v for k, v in d.items() if k in known}
        # stash any unmapped keys into summary if summary is empty
        if not kwargs.get("summary") and d.get("description"):
            kwargs["summary"] = d["description"]
        return Action(outcome_fn=fn if callable(fn) else None,
                      mutation=mut if isinstance(mut, dict) else None,
                      ctx=ctx if isinstance(ctx, dict) else {}, **kwargs)
    return Action(summary=str(action))


# ---------------------------------------------------------------------------
# individual checks — each returns (name, passed, detail, refutation|None)
# ---------------------------------------------------------------------------
def _chk_outcome_noop(a: Action) -> tuple:
    """The Blake lesson: does this mutation ACTUALLY change state, verified?"""
    name = "outcome_effective"
    m = a.mutation
    # injected reality re-check wins — it queried the real world
    if callable(a.outcome_fn):
        try:
            res = a.outcome_fn()
        except Exception as e:  # a probe that blew up is not a verified success
            return (name, False, f"outcome_fn raised: {e}", None)
        achieved, why = (res if isinstance(res, tuple) else (res, ""))
        if not achieved:
            return (name, False, why or "outcome_fn reported no effective change",
                    f"NO-OP: the action does not achieve its goal — {why or 'reality re-check shows no state change'}. "
                    "a change that changes nothing is a confident lie; abort and fix the real gate.")
    if isinstance(m, dict):
        kind = str(m.get("kind", a.kind))
        if m.get("effective") is False or m.get("changed") is False:
            return (name, False, "mutation flagged effective=False",
                    "NO-OP: mutation self-reports no effective change; abort.")
        if "before" in m and "after" in m and m["before"] == m["after"]:
            return (name, False, f"before == after ({m['before']!r})",
                    f"NO-OP: state before == state after ({m['before']!r}); the mutation is a no-op, abort.")
        if kind in ("perm_grant", "permission", "assignment"):
            if m.get("before_assigned") and m.get("after_assigned"):
                return (name, False, "target already had the permission",
                        f"NO-OP perm grant: the target already holds '{m.get('permset','it')}' — granting again "
                        "changes nothing (Blake trap). the real gap is elsewhere (FLS/object perm/sharing); abort.")
            mc = m.get("member_count")
            if mc is not None and mc == 0:
                return (name, False, "grant targets zero members",
                        f"NO-OP perm grant: '{m.get('permset','the perm set')}' would be assigned to 0 members — "
                        "grants nothing; abort and target real users.")
    return (name, True, "effective change verified" if (m or a.outcome_fn) else "no mutation to check", None)


def _chk_broadcast(a: Action) -> tuple:
    """Refute a spray/broadcast-shaped outreach: snipe don't spray (HARD RAIL 5)."""
    name = "targeting_snipe_not_spray"
    outreachy = a.kind in ("draft", "outreach", "message", "dm", "email") or a.is_send
    scope = (a.scope or "").lower()
    hit = None
    if outreachy and scope in _BROADCAST_SCOPE:
        hit = f"scope='{scope}'"
    elif outreachy and _BROADCAST_TEXT.search(a.blob):
        hit = f"broadcast phrasing in text"
    elif outreachy and re.search(r"\b(all|entire|every)\b", (a.target or ""), re.IGNORECASE):
        hit = f"crowd target='{a.target}'"
    if hit:
        return (name, False, hit,
                f"SPRAY-SHAPE: this is a broadcast, not a snipe ({hit}). his doctrine is snipe don't spray — "
                "cold blasting made $0 and burned domains. abort; target one hand-raised, intent-established person.")
    return (name, True, "single-target / not outreach", None)


def _chk_send_fence(a: Action) -> tuple:
    """Only Operator sends. Work-lane human-outbound is fenced to drafts (HARD RAIL 6)."""
    name = "send_fence"
    if a.is_send and (a.lane == "work" or a.surface in _WORK_SURFACE):
        return (name, False, f"is_send on work surface '{a.surface or a.lane}'",
                "SEND-FENCE: work lane never sends outward from the clone — only Operator sends. "
                "stage a draft instead of sending; abort.")
    return (name, True, "not a fenced send", None)


def _chk_lane_firewall(a: Action) -> tuple:
    """No hustle/stack identity or AI trace on a work/employer surface (RAILS 3 + 4)."""
    name = "lane_firewall"
    on_work = a.lane == "work" or a.surface in _WORK_SURFACE
    if on_work and _STACK_TRACE.search(a.blob):
        m = _STACK_TRACE.search(a.blob).group(0)
        return (name, False, f"stack/hustle marker '{m}' on work surface",
                f"LANE BREACH: '{m}' is hustle/stack identity landing on a work surface — the two worlds are "
                "air-gapped, this correlates the operator. abort.")
    if (a.surface in _SF_SURFACE or on_work) and _AI_TRACE.search(a.blob):
        m = _AI_TRACE.search(a.blob).group(0)
        return (name, False, f"AI trace '{m}' on work/SF surface",
                f"AI-TRACE BREACH: '{m}' would read as automation on a Salesforce/employer surface — all SF output "
                "must read as Operator's own. abort / strip the tell.")
    return (name, True, "no cross-lane / AI trace", None)


def _chk_doctrine(a: Action) -> tuple:
    """Gate through Operator's modeled judgment; a REJECT is a refutation."""
    name = "doctrine_would_alex_approve"
    if _dm is None or not a.summary:
        return (name, True, "doctrine gate unavailable / no summary", None)
    try:
        r = _dm.score(a.summary, a.ctx or None)
    except Exception as e:
        return (name, True, f"doctrine gate errored ({e}) — rails still hold", None)
    if r.get("alex_would") == _dm.REJECT:
        pid = next((m["id"] for m in r.get("matched_principles", [])), "?")
        return (name, False, f"decision_modeling REJECT [{pid}] conf={r.get('confidence')}",
                f"DOCTRINE REJECT: {r.get('why')} (principle: {pid}). abort — Operator would not approve this.")
    return (name, True, f"decision_modeling {r.get('alex_would')} (via {r.get('via')})",
            None if r.get("via") != "default" else "no strong doctrine read (unknown action)")


_DETERMINISTIC = (_chk_outcome_noop, _chk_broadcast, _chk_send_fence, _chk_lane_firewall, _chk_doctrine)


# ---------------------------------------------------------------------------
# the gate
# ---------------------------------------------------------------------------
def verify(action: Any, *, allow_model: bool | None = None) -> dict:
    """Red-team a proposed action before it fires. Returns {safe, verdict, refutations, checks}.

    Deterministic checks are total and run first. A single cheap local-model refutation pass is
    consulted ONLY for a genuine judgment call (no deterministic refutation, no clear doctrine
    read) and ONLY if ctx['model_fn'] is injected + model use is allowed. safe=False on any
    refutation — the caller MUST abort.
    """
    a = _normalize(action)
    checks: list[dict] = []
    refutations: list[str] = []

    for fn in _DETERMINISTIC:
        n, passed, detail, refutation = fn(a)
        checks.append({"check": n, "passed": bool(passed), "detail": detail})
        if not passed and refutation:
            refutations.append(refutation)

    # escalation: genuine judgment call only (deterministic layer clean, doctrine had no read)
    no_read = any(c["check"] == "doctrine_would_alex_approve"
                  and c["passed"] and c["detail"].endswith("via default)") for c in checks)
    mutating = bool(a.mutation) or a.is_send or a.kind in ("sf_change", "perm_grant", "draft", "outreach")
    allow = a.ctx.get("allow_model", False) if allow_model is None else allow_model
    if not refutations and no_read and mutating and allow and callable(a.ctx.get("model_fn")):
        try:
            out = a.ctx["model_fn"](a) or {}
        except Exception:
            out = {}
        if isinstance(out, dict) and out.get("safe") is False:
            why = out.get("refutation") or out.get("why") or "model refuted the action"
            refutations.append(f"MODEL REFUTATION: {why}")
            checks.append({"check": "model_refutation", "passed": False, "detail": why})
        elif out:
            checks.append({"check": "model_refutation", "passed": True,
                           "detail": out.get("why", "model found no refutation")})

    safe = not refutations
    return {
        "safe": safe,
        "verdict": "safe" if safe else "unsafe",
        "refutations": refutations,
        "checks": checks,
    }


# ---------------------------------------------------------------------------
def _smoke() -> int:
    fails: list[str] = []

    # (a) Blake-style no-op perm grant — target already holds the perm set.
    noop_grant = Action(
        kind="perm_grant",
        summary="assign the Rebate_Connector_Access permission set to the SP portal integration user",
        lane="work", surface="salesforce",
        mutation={"kind": "perm_grant", "permset": "Rebate_Connector_Access",
                  "before_assigned": True, "after_assigned": True},
    )
    # (b) group-broadcast auto-draft.
    broadcast = Action(
        kind="draft",
        summary="auto-draft and stage a message pitching the free scan",
        text="stage an auto-generated broadcast to every member of the roofing slack channel",
        lane="hustle", scope="broadcast", target="all channel members",
    )
    # (c) genuinely-correct targeted fix — single scope, real state change, no rail issue.
    good_fix = Action(
        kind="sf_change",
        summary="revert UserOpportunityController to without-sharing for the single affected account scope "
                "to restore portal coverage",
        lane="work", surface="salesforce",
        mutation={"kind": "config", "before": "with sharing", "after": "without sharing"},
        outcome_fn=lambda: (True, "coverage re-check: 92% (up from 53%)"),
    )

    cases = [
        ("noop-perm-grant", noop_grant, False, "outcome_effective"),
        ("group-broadcast-draft", broadcast, False, "targeting_snipe_not_spray"),
        ("targeted-correct-fix", good_fix, True, None),
    ]

    print("=== self_verify smoke ===")
    for label, act, want_safe, want_check in cases:
        r = verify(act)
        ok = r["safe"] == want_safe
        if want_check is not None:
            failed_checks = [c["check"] for c in r["checks"] if not c["passed"]]
            ok = ok and want_check in failed_checks
        print(f"\n[{label}] safe={r['safe']} (want {want_safe})  verdict={r['verdict']}")
        for c in r["checks"]:
            mark = "ok " if c["passed"] else "REFUTE"
            print(f"   {mark} {c['check']}: {c['detail']}")
        for ref in r["refutations"]:
            print(f"   -> {ref}")
        if not ok:
            fails.append(f"{label}: safe={r['safe']} want {want_safe}, "
                         f"refuted={[c['check'] for c in r['checks'] if not c['passed']]}")

    # extra: an AI trace on SF must be refuted even if everything else is clean.
    r = verify(Action(kind="sf_change", summary="add a chatter note", lane="work",
                      surface="salesforce", text="config updated — generated by Claude"))
    if r["safe"]:
        fails.append("AI trace on SF surface must REFUTE")

    # extra: a no-op caught by an injected reality re-check (outcome_fn -> not achieved).
    r = verify(Action(kind="perm_grant", summary="grant object perms via a perm set",
                      lane="work", surface="salesforce",
                      outcome_fn=lambda: (False, "FLS still hides the field; grant is a no-op")))
    if r["safe"]:
        fails.append("outcome_fn no-op must REFUTE")

    # extra: a work-lane send must hit the send-fence.
    r = verify(Action(kind="email", summary="send the status email to the VP", lane="work",
                      surface="outlook", is_send=True, scope="single", target="the VP"))
    if r["safe"]:
        fails.append("work-lane send must REFUTE (send-fence)")

    print()
    if fails:
        print("SMOKE FAIL:")
        for m in fails:
            print("  -", m)
        return 1
    print("SMOKE OK — no-op perm grant REJECTED (Blake trap), group broadcast REJECTED (snipe not spray), "
          "targeted verified fix PASSED. AI-trace + outcome_fn no-op + send-fence carve-outs held.")
    return 0


if __name__ == "__main__":
    raise SystemExit(_smoke())
