#!/usr/bin/env python3
"""GitHub loop for the WORK-lane SFDC engineer — open PRs, read review feedback, stage prod.

The engineer works ENTIRELY on feature branches: it opens a PR against a working base
(develop / an integration branch), reads back the review comments (human + Copilot/Cursor
bots), and STAGES a prod-promotion summary for Operator's real gated CompanyA pipeline. It never
merges, never force-pushes, and never promotes to prod on its own.

Design rules baked in:
  - **Deterministic-first.** Bot detection, base-branch guarding, and scrubbing are pure logic
    so recurring PR mechanics never burn a premium AI call.
  - **DRY-RUN by default.** Every git/gh MUTATION returns the exact command it WOULD run; it
    only executes when dry=False. Reads (review feedback) run live — they're safe + free.
  - **Zero AI/stack trace on employer surfaces.** `_scrub` hard-rejects any title/body carrying
    a Claude/stack/assistant/generated-by/bot marker before it can reach a CompanyA PR.
  - **Protected branches are untouchable.** A PR is never based on (nor a head of) main / master
    / prod; open_pr refuses.

This module carries no AI/stack trace itself and authors no SF-facing content.
"""
from __future__ import annotations

import json
import os
import shlex
import subprocess
from typing import Any

from core import BASE_DIR  # noqa: F401  (repo convention; anchors this as work-lane core)

REPO = "redactedind/AG-CDT-SALESFORCE"
SF_REPO_DIR = "/home/user/AG-CDT-SALESFORCE"

# Branches the engineer must never base a PR on, push to, or set as a PR head.
PROTECTED_BRANCHES = frozenset({"main", "master", "prod", "production", "develop"})
# `develop` is a valid PR *base* (integration target) but never a push/head target.
PROTECTED_PUSH_ONLY = frozenset({"develop"})

# Employer-visible strings that must NEVER appear in a CompanyA PR title/body/branch. Matching
# is substring, case-insensitive — these are register mistakes, so cheap to catch mechanically.
AI_TRACE_MARKERS = (
    "claude",
    "anthropic",
    "opus",
    "sonnet",
    "haiku",
    "assistant",
    "generated by",
    "generated with",
    "co-authored-by: claude",
    "ai-generated",
    "ai generated",
    "chatgpt",
    "openai",
    "gpt-4",
    "gpt-5",
    "llm",
    "language model",
    "claude-stack",
    "claude stack",
    "🤖",
    "emoji-bot",
    "stack agent",
)

# Reviewer logins / suffixes that mark an automated (non-human) reviewer.
_BOT_LOGIN_MARKERS = ("[bot]", "copilot", "cursor", "dependabot", "github-actions", "-bot", "bot-")


class ScrubError(ValueError):
    """Raised when text destined for an employer-visible surface carries an AI/stack trace."""


def _scrub(text: str, *, field: str = "text") -> str:
    """Return `text` unchanged iff it's clean; raise ScrubError on any AI/stack marker.

    Reject rather than silently strip: a body that mentions Claude was authored wrong upstream,
    and silently editing employer-visible prose could change its meaning. The caller fixes the
    source.
    """
    if text is None:
        return ""
    low = text.lower()
    for marker in AI_TRACE_MARKERS:
        if marker in low:
            raise ScrubError(
                f"{field} contains a forbidden AI/stack marker {marker!r} -- refuse to put on a CompanyA PR"
            )
    return text


def _is_bot(login: str) -> bool:
    low = (login or "").lower()
    return any(m in low for m in _BOT_LOGIN_MARKERS)


def _gh_env() -> dict[str, str]:
    """gh must use its own keyring auth (the CompanyA account with org SSO), not a stack token.

    `core.__init__` runs load_dotenv, which injects a stack GITHUB_TOKEN that cannot resolve the
    CompanyA repo (GraphQL "Could not resolve to a Repository"). Strip those overrides so gh falls
    back to its stored credentials for account 'redacted_redacted'.
    """
    env = dict(os.environ)
    for k in ("GITHUB_TOKEN", "GH_TOKEN", "GH_ENTERPRISE_TOKEN"):
        env.pop(k, None)
    return env


def _run(cmd: list[str], *, dry: bool) -> dict[str, Any]:
    """Execute (dry=False) or describe (dry=True) a git/gh command.

    Returns a uniform envelope so callers/tests read the same shape either way.
    """
    printable = " ".join(shlex.quote(c) for c in cmd)
    if dry:
        return {"dry_run": True, "command": printable, "executed": False}
    proc = subprocess.run(cmd, capture_output=True, text=True, env=_gh_env())
    return {
        "dry_run": False,
        "command": printable,
        "executed": True,
        "returncode": proc.returncode,
        "stdout": proc.stdout.strip(),
        "stderr": proc.stderr.strip(),
    }


def _gh_read(args: list[str]) -> Any:
    """Run a READ-only gh/gh-api command and parse JSON. Reads always execute (safe + free)."""
    proc = subprocess.run(["gh", *args], capture_output=True, text=True, env=_gh_env())
    if proc.returncode != 0:
        return {"_error": proc.stderr.strip() or proc.stdout.strip(), "_returncode": proc.returncode}
    out = proc.stdout.strip()
    if not out:
        return None
    try:
        return json.loads(out)
    except json.JSONDecodeError:
        return {"_raw": out}


def open_pr(
    branch: str,
    title: str,
    body: str,
    base: str = "develop",
    dry: bool = True,
) -> dict[str, Any]:
    """Open a feature-branch PR via gh. DRY-RUN by default.

    Guards, in order (all deterministic):
      1. head branch must not be a protected branch;
      2. base must not be a protected *push* target (main/master/prod) -- develop is an allowed base;
      3. title + body pass `_scrub` (employer-visible, zero AI/stack trace);
      4. branch name passes `_scrub` (branch is visible in the PR + git ref).
    """
    if not branch:
        raise ValueError("branch is required")
    if branch in PROTECTED_BRANCHES:
        raise ValueError(f"refuse to open a PR whose HEAD is protected branch {branch!r}")
    if base in (PROTECTED_BRANCHES - PROTECTED_PUSH_ONLY):
        # main / master / prod / production are never a valid PR base for the engineer.
        raise ValueError(f"refuse to base a PR on protected branch {base!r} -- use develop or an integration branch")

    clean_branch = _scrub(branch, field="branch")
    clean_title = _scrub(title, field="title")
    clean_body = _scrub(body, field="body")

    cmd = [
        "gh", "pr", "create",
        "--repo", REPO,
        "--base", base,
        "--head", clean_branch,
        "--title", clean_title,
        "--body", clean_body,
    ]
    result = _run(cmd, dry=dry)
    result.update({"branch": clean_branch, "base": base, "title": clean_title})
    return result


def get_review_feedback(pr_number: int) -> dict[str, Any]:
    """Read PR review comments (human + Copilot/Cursor/bot) and return actionable items.

    Merges two sources:
      - `gh pr view <n> --json reviews,comments` -- top-level review bodies + issue comments;
      - `gh api .../pulls/<n>/comments`          -- inline line-anchored review comments.

    Returns {pr, actionable:[{reviewer, path, line, body, is_bot}], counts, note}. A PR with no
    review yet (Copilot may not have run) returns an empty actionable list + a note, never an error.
    """
    items: list[dict[str, Any]] = []

    pv = _gh_read(["pr", "view", str(pr_number), "--repo", REPO, "--json", "reviews,comments,state,title"])
    if isinstance(pv, dict) and pv.get("_error"):
        return {
            "pr": pr_number,
            "actionable": [],
            "counts": {"total": 0, "bot": 0, "human": 0},
            "note": f"could not read PR #{pr_number}: {pv['_error']}",
        }

    pv = pv or {}
    for rev in pv.get("reviews") or []:
        body = (rev.get("body") or "").strip()
        if not body:
            continue  # an approval/comment with no text is not actionable
        login = (rev.get("author") or {}).get("login", "")
        items.append(
            {
                "reviewer": login,
                "path": None,
                "line": None,
                "body": body,
                "is_bot": _is_bot(login),
                "source": "review",
                "state": rev.get("state"),
            }
        )
    for com in pv.get("comments") or []:
        body = (com.get("body") or "").strip()
        if not body:
            continue
        login = (com.get("author") or {}).get("login", "")
        items.append(
            {
                "reviewer": login,
                "path": None,
                "line": None,
                "body": body,
                "is_bot": _is_bot(login),
                "source": "issue_comment",
            }
        )

    inline = _gh_read(["api", f"repos/{REPO}/pulls/{pr_number}/comments", "--paginate"])
    if isinstance(inline, list):
        for com in inline:
            body = (com.get("body") or "").strip()
            if not body:
                continue
            login = (com.get("user") or {}).get("login", "")
            items.append(
                {
                    "reviewer": login,
                    "path": com.get("path"),
                    "line": com.get("line") or com.get("original_line"),
                    "body": body,
                    "is_bot": _is_bot(login),
                    "source": "inline",
                }
            )

    bot = sum(1 for i in items if i["is_bot"])
    note = ""
    if not items:
        note = "no review comments yet (Copilot/Cursor may not have run) -- nothing to action"
    return {
        "pr": pr_number,
        "title": pv.get("title"),
        "state": pv.get("state"),
        "actionable": items,
        "counts": {"total": len(items), "bot": bot, "human": len(items) - bot},
        "note": note,
    }


def promotion_gate(pr_number: int) -> dict[str, Any]:
    """Stage a prod-promotion summary for the review queue. NEVER auto-promotes.

    Reads the PR's review feedback and derives whether it's *staged-ready* for Operator to promote
    through the real gated CompanyA sandbox->github->prod pipeline. `ready_for_prod` is only ever
    a recommendation surfaced to a human -- this function performs no deploy and no merge.
    """
    fb = get_review_feedback(pr_number)
    # Blocking = any bot/human review item that looks like a change request (heuristic, deterministic).
    blocking = [
        i
        for i in fb["actionable"]
        if i.get("state") == "CHANGES_REQUESTED"
        or _looks_like_change_request(i["body"])
    ]
    ready = fb["counts"]["total"] > 0 and not blocking
    return {
        "pr": pr_number,
        "ready_for_prod": bool(ready),
        "blocking_review_items": blocking,
        "review_summary": fb["counts"],
        "auto_promoted": False,
        "note": "awaiting Operator + gated CompanyA pipeline (sandbox -> github -> prod); this stage never deploys",
    }


_CHANGE_REQUEST_HINTS = (
    "should be",
    "must ",
    "please change",
    "please fix",
    "needs to",
    "remove ",
    "don't ",
    "do not ",
    "vulnerab",
    "security",
    "bug",
    "incorrect",
    "will fail",
    "breaks",
    "regression",
    "with sharing",
    "without sharing",
    "sharing",
)


def _looks_like_change_request(body: str) -> bool:
    low = (body or "").lower()
    return any(h in low for h in _CHANGE_REQUEST_HINTS)


if __name__ == "__main__":
    print("== _scrub rejects AI trace ==")
    try:
        _scrub("this PR was generated by Claude", field="body")
        raise SystemExit("FAIL: _scrub did NOT reject a body containing 'generated by Claude'")
    except ScrubError as e:
        print(f"  OK rejected: {e}")
    assert _scrub("grant SP portal apex classes to portal profiles") == "grant SP portal apex classes to portal profiles"
    print("  OK clean text passes")

    print("\n== dry-run open_pr command ==")
    dr = open_pr(
        branch="feature/SF-1234-portal-perm-fix",
        title="SF-1234: grant portal apex classes to strategic account profile",
        body="adds missing apex class access flagged by the offshore team; validated in sandbox",
        base="develop",
        dry=True,
    )
    print(f"  {dr['command']}")
    assert dr["dry_run"] and not dr["executed"]

    print("\n== open_pr refuses protected base/head ==")
    for kw in (dict(base="main"), dict(branch="main")):
        try:
            open_pr(branch=kw.get("branch", "feature/x"), title="t", body="b", base=kw.get("base", "develop"))
            raise SystemExit(f"FAIL: open_pr allowed protected {kw}")
        except ValueError as e:
            print(f"  OK refused {kw}: {e}")

    print("\n== live read: get_review_feedback ==")
    fb = None
    for pr in (382, 383):
        fb = get_review_feedback(pr)
        if fb["counts"]["total"] or not fb["note"].startswith("could not read"):
            break
    print(f"  PR #{fb['pr']} [{fb.get('state')}] -- {fb['counts']}")
    if fb["note"]:
        print(f"  note: {fb['note']}")
    for i in fb["actionable"][:6]:
        tag = "BOT" if i["is_bot"] else "HUMAN"
        loc = f" {i['path']}:{i['line']}" if i["path"] else ""
        snippet = " ".join(i["body"].split())[:110]
        print(f"  [{tag}] {i['reviewer']}{loc}: {snippet}")

    print("\n== promotion_gate (staged, never auto-promotes) ==")
    pg = promotion_gate(fb["pr"])
    print(f"  ready_for_prod={pg['ready_for_prod']} auto_promoted={pg['auto_promoted']} "
          f"blocking={len(pg['blocking_review_items'])}")
    print(f"  note: {pg['note']}")
    assert pg["auto_promoted"] is False
    print("\nSMOKE OK")
