#!/usr/bin/env python3
"""Ops dashboard generator — revenue lanes + system health in one static page.

Same pattern as tools/cost_page.py: renders one self-contained dark-theme HTML
file (frontends/ops.html) with all data baked in; works over file://, no server.
Regenerated by launchd job com.claude-stack.ops-dashboard every 5 min.

Tabs:
  1. REVENUE — every revenue lane (Stripe live numbers, Gumroad, Hun Vault,
     Intent Lead Finder, lead lists, intent strike list, persona1/social, content
     channels) + costs / ROI / savings (reuses tools.spend_dashboard).
  2. SYSTEM HEALTH — launchd jobs, endpoint up/down, diagnostician summary,
     spend breakers, disk, e2e/smoke.

READ-ONLY everywhere (Stripe GETs only). Every section degrades to
'unavailable' instead of crashing. No secrets are written into the HTML.

    PYTHONPATH=. .venv/bin/python tools/ops_dashboard.py [--print]
"""
from __future__ import annotations

import html
import json
import os
import re
import shutil
import socket
import subprocess
import sys
import urllib.request
from datetime import datetime, timedelta, timezone
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
HOME = Path.home()
OUT_HTML = BASE_DIR / "frontends" / "ops.html"
REFRESH_SECONDS = 120
UNAVAILABLE = "unavailable"


def _esc(s) -> str:
    return html.escape(str(s))


def _money(v) -> str:
    try:
        v = float(v or 0)
    except Exception:
        v = 0.0
    return f"${v:,.2f}"


def _read_json(p: Path):
    try:
        return json.loads(p.read_text())
    except Exception:
        return None


# ── data collectors (each returns a dict; failures captured per-section) ────

def collect_stripe() -> dict:
    key = None
    try:
        for line in (BASE_DIR / ".env").read_text().splitlines():
            if line.startswith("STRIPE_SECRET_KEY="):
                key = line.split("=", 1)[1].strip()
                break
    except Exception:
        pass
    if not key:
        return {"error": "no STRIPE_SECRET_KEY in .env"}

    def get(path):
        req = urllib.request.Request("https://api.stripe.com/v1/" + path)
        req.add_header("Authorization", "Bearer " + key)
        with urllib.request.urlopen(req, timeout=15) as r:
            return json.load(r)

    out = {}
    try:
        bal = get("balance")
        out["available"] = sum(x["amount"] for x in bal.get("available", [])) / 100.0
        out["pending"] = sum(x["amount"] for x in bal.get("pending", [])) / 100.0
    except Exception as e:
        out["balance_error"] = str(e)[:120]

    try:
        charges, starting_after = [], None
        for _ in range(5):  # cap pagination: 500 charges max
            q = "charges?limit=100" + (f"&starting_after={starting_after}" if starting_after else "")
            page = get(q)
            charges.extend(page.get("data", []))
            if not page.get("has_more"):
                break
            starting_after = charges[-1]["id"]
        succ = [c for c in charges if c.get("status") == "succeeded" and not c.get("refunded")]
        cutoff = (datetime.now(timezone.utc) - timedelta(days=30)).timestamp()
        out["charges_seen"] = len(charges)
        out["revenue_alltime"] = sum(c["amount"] for c in succ) / 100.0
        out["revenue_30d"] = sum(c["amount"] for c in succ if c.get("created", 0) >= cutoff) / 100.0
        out["succeeded_count"] = len(succ)
    except Exception as e:
        out["charges_error"] = str(e)[:120]

    try:
        sess = get("checkout/sessions?limit=100")
        data = sess.get("data", [])
        out["checkout_sessions_recent"] = len(data)
        out["checkout_completed"] = sum(1 for s in data if s.get("status") == "complete")
    except Exception as e:
        out["sessions_error"] = str(e)[:120]
    return out


def collect_lanes(stripe: dict) -> list[dict]:
    lanes = []
    s_rev = stripe.get("revenue_alltime")
    rail_ok = "balance_error" not in stripe and "error" not in stripe

    # Stripe rail
    lanes.append({
        "name": "Stripe payment rail",
        "status": "live" if rail_ok else "unknown",
        "revenue": _money(s_rev) if s_rev is not None else UNAVAILABLE,
        "detail": (f"{stripe.get('succeeded_count', 0)} successful charges · "
                   f"balance {_money(stripe.get('available', 0))} available") if rail_ok else stripe.get("error", UNAVAILABLE),
        "blocker": "" if (s_rev or 0) > 0 else "no purchases yet — traffic/conversion gap",
    })

    # Gumroad
    gr = BASE_DIR / "products" / "gumroad_ready"
    try:
        prods = [d for d in gr.iterdir() if d.is_dir() and not d.name.startswith("_")]
        zips = list((gr / "_packaged").glob("*.zip")) if (gr / "_packaged").exists() else []
        lanes.append({
            "name": "Gumroad digital products",
            "status": "gated",
            "revenue": "$0 (no API revenue feed)",
            "detail": f"{len(prods)} products staged, {len(zips)} packaged zips ready",
            "blocker": "Operator must log into gumroad.com once (stale publisher session) → autonomous attach",
        })
    except Exception:
        lanes.append({"name": "Gumroad digital products", "status": "unknown",
                      "revenue": UNAVAILABLE, "detail": "products/gumroad_ready unreadable", "blocker": ""})

    # Hun Vault
    try:
        src = (BASE_DIR / "products" / "self_serve" / "app.py").read_text()
        m = re.search(r"HUNS_PRODUCTS\s*=\s*\[(.*?)\n\]", src, re.S)
        n = len(re.findall(r"\(\s*[\"']", m.group(1))) if m else 0
        lanes.append({
            "name": "Hun Vault (scannerapp.dev/huns)",
            "status": "live" if n else "dormant",
            "revenue": _money(stripe.get("revenue_alltime", 0)) if rail_ok else UNAVAILABLE,
            "detail": f"{n} live Stripe buy buttons (shares the rail above — $ not double-counted)",
            "blocker": "traffic: bio links / distribution",
        })
    except Exception:
        lanes.append({"name": "Hun Vault (/huns)", "status": "unknown",
                      "revenue": UNAVAILABLE, "detail": "app.py unreadable", "blocker": ""})

    # Intent Lead Finder service
    svc = _read_json(BASE_DIR / "data" / "hustle" / "intent_service.json") or {}
    lanes.append({
        "name": "Intent Lead Finder ($99/mo)",
        "status": "live" if svc.get("checkout_url") else "unknown",
        "revenue": "$0 — 0 subscribers",
        "detail": f"checkout live since {svc.get('created', '?')} · +$249 feed & $79 tripwire SKUs" if svc else UNAVAILABLE,
        "blocker": "first subscriber (distribution via response queue)",
    })

    # Lead-list inventory
    inv = BASE_DIR / "data" / "hustle" / "leadgen_inventory.jsonl"
    try:
        n = sum(1 for line in inv.read_text().splitlines() if line.strip())
        lanes.append({
            "name": "Lead-list inventory",
            "status": "live" if n else "dormant",
            "revenue": "$0",
            "detail": f"{n} inventory records in leadgen_inventory.jsonl" + (" (EMPTY)" if not n else ""),
            "blocker": "inventory file empty — pipeline not writing" if not n else "",
        })
    except Exception:
        lanes.append({"name": "Lead-list inventory", "status": "unknown",
                      "revenue": UNAVAILABLE, "detail": "leadgen_inventory.jsonl unreadable", "blocker": ""})

    # Intent strike list
    try:
        txt = (BASE_DIR / "data" / "hustle" / "INTENT_STRIKE_LIST.md").read_text()
        m = re.search(r"(\d+)\s+live buyers", txt)
        hdr = re.search(r"INTENT STRIKE LIST\s+—\s+(.+)", txt)
        lanes.append({
            "name": "Intent strike list (daily battle board)",
            "status": "live",
            "revenue": "— (lead source, not a SKU)",
            "detail": f"{m.group(1) if m else '?'} live buyers ranked · refreshed {hdr.group(1).strip() if hdr else '?'}",
            "blocker": "replies capped 1/run, 4/day (fresh-account suspension risk)",
        })
    except Exception:
        lanes.append({"name": "Intent strike list", "status": "unknown",
                      "revenue": UNAVAILABLE, "detail": "INTENT_STRIKE_LIST.md unreadable", "blocker": ""})

    # persona1 / social growth
    try:
        lines = (BASE_DIR / "data" / "hustle" / "ima_growth.jsonl").read_text().strip().splitlines()
        g = json.loads(lines[-1])
        lanes.append({
            "name": "persona1 social funnel (TikTok)",
            "status": "live (throttled)",
            "revenue": "$0 attributed",
            "detail": (f"{g.get('followers', 0):,} followers · {g.get('likes', 0):,} likes · "
                       f"{g.get('recent_videos', 0)} recent vids, {g.get('recent_views_sum', 0):,} views "
                       f"(as of {str(g.get('ts', ''))[:16]})"),
            "blocker": "account throttled (10K followers, ~300 views) — reach suppressed",
        })
    except Exception:
        lanes.append({"name": "persona1 social funnel", "status": "unknown",
                      "revenue": UNAVAILABLE, "detail": "ima_growth.jsonl unreadable", "blocker": ""})

    # Content channel empire
    profiles = [p.name.replace(".chrome-cdp-profile-", "") for p in HOME.glob(".chrome-cdp-profile-*") if p.is_dir()]
    lanes.append({
        "name": "Content channel empire",
        "status": "live",
        "revenue": "$0 direct",
        "detail": "7 channels (persona1/persona2/persona4/persona3/persona5/persona6/persona7) · "
                  f"CDP profiles present: {', '.join(sorted(profiles)) or 'none found'}",
        "blocker": "distribution feeds funnels; no direct monetization link surface",
    })
    return lanes


def collect_spend() -> tuple[dict, dict]:
    sys.path.insert(0, str(BASE_DIR))
    try:
        from tools.spend_dashboard import build_report, lifetime_estimate
        report = build_report()
    except Exception as e:
        return {"_error": str(e)[:200]}, {}
    try:
        lifetime = lifetime_estimate()
    except Exception:
        lifetime = {}
    return report, lifetime


def collect_launchd() -> dict:
    try:
        out = subprocess.run(["launchctl", "list"], capture_output=True, text=True, timeout=20).stdout
    except Exception as e:
        return {"_error": str(e)[:120]}
    jobs = []
    for line in out.splitlines()[1:]:
        parts = line.split("\t")
        if len(parts) != 3 or "claude-stack" not in parts[2]:
            continue
        pid, status, label = parts
        jobs.append({"pid": pid, "status": status, "label": label})
    running = [j for j in jobs if j["pid"] != "-"]
    failed = [j for j in jobs if j["status"] not in ("0", "-") and not j["status"].startswith("-")]
    return {"total": len(jobs), "running": len(running),
            "idle": len(jobs) - len(running) - len(failed), "failed": failed}


def collect_endpoints() -> list[dict]:
    eps = [("self-serve shop", 8102), ("brain/gateway", 8300), ("work gateway", 8330),
           ("chrome-cdp persona1", 18801), ("chrome-cdp #2", 18802), ("chrome-cdp #3", 18803),
           ("SearXNG", 8890), ("Ollama", 11434)]
    out = []
    for name, port in eps:
        try:
            with socket.create_connection(("127.0.0.1", port), timeout=2):
                up = True
        except Exception:
            up = False
        out.append({"name": name, "port": port, "up": up})
    return out


def collect_diag() -> dict:
    d = _read_json(BASE_DIR / "data" / "diagnostic_report.json")
    if not d:
        return {"_error": "diagnostic_report.json unreadable"}
    counts = d.get("finding_counts", {})
    crits = [f.get("message", f.get("signature", "?"))
             for f in d.get("findings", []) if f.get("level") == "critical"][:5]
    return {"as_of": d.get("as_of_iso", d.get("as_of", "?")), "counts": counts, "criticals": crits}


def collect_breakers() -> dict:
    out = {}
    g = _read_json(HOME / ".openrouter-budget-guard.state.json")
    out["budget_guard"] = ({"tripped": g.get("tripped"), "warned": g.get("warned"),
                            "month": g.get("month")} if g else None)
    b = _read_json(HOME / ".burn-rate-guard.state.json")
    if b:
        hist = b.get("history", [])
        out["burn_guard"] = {"tripped": b.get("tripped"),
                             "last_usage": hist[-1].get("usage") if hist else None}
    else:
        out["burn_guard"] = None
    return out


def collect_disk() -> dict:
    try:
        u = shutil.disk_usage("/")
        return {"free_gb": u.free / 1e9, "total_gb": u.total / 1e9,
                "pct_used": 100 * (u.total - u.free) / u.total}
    except Exception as e:
        return {"_error": str(e)[:120]}


def collect_smoke() -> str:
    # no canonical smoke/e2e result file found in repo; check a couple of spots
    for p in [BASE_DIR / "data" / "smoke_result.json", BASE_DIR / "data" / "e2e_result.json"]:
        d = _read_json(p)
        if d:
            return json.dumps(d)[:200]
    return UNAVAILABLE


# ── render ───────────────────────────────────────────────────────────────────

def _card(label, value, sub="", tone="") -> str:
    sub_html = f'<div class="sub">{_esc(sub)}</div>' if sub else ""
    return (f'<div class="card {tone}"><div class="lbl">{_esc(label)}</div>'
            f'<div class="val">{_esc(value)}</div>{sub_html}</div>')


def _table(headers, rows_html) -> str:
    if not rows_html:
        return f'<p class="empty">— {UNAVAILABLE} —</p>'
    head = "".join(f"<th>{_esc(h)}</th>" for h in headers)
    return f'<table><thead><tr>{head}</tr></thead><tbody>{"".join(rows_html)}</tbody></table>'


def build_html(data: dict) -> str:
    stripe = data["stripe"]
    lanes = data["lanes"]
    report, lifetime = data["spend"]
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # revenue hero
    rev_all = stripe.get("revenue_alltime")
    rev_30 = stripe.get("revenue_30d")
    can = report.get("canonical", {}) or {}
    alltime = can.get("alltime", {}) if "_error" not in can else {}
    vs_max = can.get("vs_max", {}) if "_error" not in can else {}
    spend_all = float(alltime.get("api_cost", 0) or 0)
    monthly_cost = float(vs_max.get("monthly_avg_api_spend", 0) or 0)
    rev_f = float(rev_all or 0)
    net = rev_f - spend_all
    roi = f"{((rev_f - spend_all) / spend_all) * 100:,.0f}%" if spend_all > 0 else "n/a"
    saved = float(alltime.get("net_saved", 0) or 0)

    hero = "".join([
        _card("Revenue (all-time, Stripe)", _money(rev_all) if rev_all is not None else UNAVAILABLE,
              f"{stripe.get('succeeded_count', '?')} charges", "good" if rev_f > 0 else "bad"),
        _card("Revenue (last 30d)", _money(rev_30) if rev_30 is not None else UNAVAILABLE, "", "accent"),
        _card("Stripe balance", _money(stripe.get("available", 0)),
              f"pending {_money(stripe.get('pending', 0))}", ""),
        _card("Paid API spend (all-time)", _money(spend_all),
              f"~{_money(monthly_cost)}/mo run-rate", "bad" if spend_all > 1 else "good"),
        _card("Net (rev − cost)", _money(net), f"ROI {roi}", "good" if net >= 0 else "bad"),
        _card("Saved vs paid equivalents", _money(saved),
              "estimate: local Ollama/SearXNG/free-tier vs paid APIs", "good"),
    ])

    # lanes table
    tone = {"live": "good", "live (throttled)": "warn", "gated": "warn",
            "dormant": "muted", "unknown": "muted"}
    lane_rows = []
    for l in lanes:
        t = tone.get(l["status"], "")
        lane_rows.append(
            f'<tr><td><b>{_esc(l["name"])}</b></td>'
            f'<td><span class="pill {t}">{_esc(l["status"])}</span></td>'
            f'<td>{_esc(l["revenue"])}</td>'
            f'<td class="wrap">{_esc(l["detail"])}</td>'
            f'<td class="wrap muted">{_esc(l["blocker"] or "—")}</td></tr>')
    lanes_tbl = _table(["Lane", "Status", "Revenue to date", "Detail", "Blocker"], lane_rows)

    # costs / ROI / savings detail
    today = can.get("today", {}) if "_error" not in can else {}
    wk = report.get("seven_day", {}) or {}
    savings_rows = [
        f'<tr><td class="k">Paid API spend today</td><td>{_money(today.get("api_cost", 0))}</td></tr>',
        f'<tr><td class="k">Paid API spend 7d</td><td>{_money(wk.get("paid_spend", 0))}</td></tr>',
        f'<tr><td class="k">Paid API spend all-time</td><td>{_money(spend_all)} ({alltime.get("api_calls", 0)} calls)</td></tr>',
        f'<tr><td class="k">Monthly cost run-rate</td><td>{_money(monthly_cost)}/mo</td></tr>',
        f'<tr><td class="k">Gross cost avoided (all-time, est.)</td><td>{_money(alltime.get("avoided_cost", 0))}</td></tr>',
        f'<tr><td class="k">Net saved (all-time, est.)</td><td><b class="good">{_money(saved)}</b> over {alltime.get("days_active", 0)} days</td></tr>',
        f'<tr><td class="k">Savings vs $100/mo max plan (est.)</td><td>{_money(vs_max.get("savings_vs_max", 0))}</td></tr>',
    ]
    if lifetime.get("scenarios"):
        lk = lifetime["scenarios"].get("likely", {})
        savings_rows.append(
            f'<tr><td class="k">Lifetime value, "likely" scenario (est.)</td>'
            f'<td>{_money(lk.get("total_value", 0))}</td></tr>')
    cost_tbl = _table(["Costs / ROI / savings", ""], savings_rows)
    cost_note = ('Savings are estimates: value of local Ollama inference, self-hosted SearXNG, '
                 'and free-tier API arbitrage priced at paid-equivalent rates '
                 '(tools/spend_dashboard ledger). Revenue is Stripe-verified, read-only.')

    # ── health tab ───────────────────────────────────────────────────────────
    ld = data["launchd"]
    if "_error" in ld:
        ld_html = f'<p class="empty">launchd: {_esc(ld["_error"])}</p>'
    else:
        fail_rows = [f'<tr><td>{_esc(j["label"])}</td><td class="bad">exit {_esc(j["status"])}</td></tr>'
                     for j in ld["failed"]]
        ld_html = ("".join([
            _card("claude-stack jobs", ld["total"], "loaded in launchd"),
            _card("Running now", ld["running"], "", "good"),
            _card("Idle (clean)", ld["idle"], "", ""),
            _card("Failed (exit≠0)", len(ld["failed"]), "", "bad" if ld["failed"] else "good"),
        ]))
        ld_html = (f'<div class="cards">{ld_html}</div>'
                   + (f'<h3>Non-zero exit jobs</h3>{_table(["Label", "Last exit"], fail_rows)}'
                      if fail_rows else '<p class="muted">No failing jobs.</p>'))

    ep_rows = [f'<tr><td>{_esc(e["name"])}</td><td>:{e["port"]}</td>'
               f'<td><span class="pill {"good" if e["up"] else "bad"}">{"UP" if e["up"] else "DOWN"}</span></td></tr>'
               for e in data["endpoints"]]
    ep_tbl = _table(["Endpoint", "Port", "State"], ep_rows)

    dg = data["diag"]
    if "_error" in dg:
        diag_html = f'<p class="empty">diagnostician: {_esc(dg["_error"])}</p>'
    else:
        c = dg["counts"]
        crit_list = "".join(f"<li>{_esc(m)}</li>" for m in dg["criticals"]) or "<li>none</li>"
        diag_html = (f'<div class="cards">'
                     + _card("Critical", c.get("critical", 0), "", "bad" if c.get("critical") else "good")
                     + _card("Warn", c.get("warn", 0), "", "warn")
                     + _card("Info", c.get("info", 0), "", "")
                     + f'</div><p class="muted">as of {_esc(dg["as_of"])}</p>'
                     f'<h3>Top criticals</h3><ul class="crits">{crit_list}</ul>')

    br = data["breakers"]
    def br_row(name, st):
        if st is None:
            return f'<tr><td class="k">{name}</td><td>{UNAVAILABLE}</td></tr>'
        tripped = st.get("tripped")
        extra = ""
        if "month" in st:
            extra = f' · month {st["month"]} · warned={st.get("warned")}'
        if st.get("last_usage") is not None:
            extra = f' · last usage ${st["last_usage"]:.2f}'
        cls = "bad" if tripped else "good"
        return (f'<tr><td class="k">{name}</td>'
                f'<td><span class="pill {cls}">{"TRIPPED" if tripped else "armed / not tripped"}</span>'
                f'<span class="muted">{_esc(extra)}</span></td></tr>')
    br_tbl = _table(["Spend breaker", "State"],
                    [br_row("OpenRouter budget guard", br.get("budget_guard")),
                     br_row("Burn-rate guard", br.get("burn_guard"))])

    dk = data["disk"]
    disk_txt = (f'{dk["free_gb"]:.1f} GB free of {dk["total_gb"]:.0f} GB ({dk["pct_used"]:.0f}% used)'
                if "_error" not in dk else UNAVAILABLE)
    misc_tbl = _table(["Misc", ""], [
        f'<tr><td class="k">Disk (/)</td><td>{_esc(disk_txt)}</td></tr>',
        f'<tr><td class="k">Last e2e/smoke result</td><td>{_esc(data["smoke"])}</td></tr>',
        f'<tr><td class="k">Generated at</td><td>{_esc(now)}</td></tr>',
    ])

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="refresh" content="{REFRESH_SECONDS}">
<title>Ops Dashboard · Claude Stack</title>
<style>
:root{{--bg:#0b0e14;--panel:#141925;--line:#222a3a;--ink:#e6e9ef;--muted:#8a93a6;
--good:#3ddc97;--bad:#ff6b6b;--warn:#ffd166;--accent:#7aa2ff;}}
*{{box-sizing:border-box}}
body{{margin:0;background:var(--bg);color:var(--ink);
font:14px/1.5 -apple-system,BlinkMacSystemFont,"SF Pro Text",system-ui,sans-serif;
-webkit-font-smoothing:antialiased;padding:28px 22px 60px}}
h1{{font-size:20px;margin:0 0 2px}}
h2{{font-size:13px;text-transform:uppercase;letter-spacing:1.2px;color:var(--muted);
margin:26px 0 10px;font-weight:600}}
h3{{font-size:12px;text-transform:uppercase;letter-spacing:1px;color:var(--muted);margin:18px 0 8px}}
.head{{display:flex;justify-content:space-between;align-items:baseline;flex-wrap:wrap;gap:8px;
border-bottom:1px solid var(--line);padding-bottom:14px;margin-bottom:14px}}
.asof{{color:var(--muted);font-size:12px}} .asof b{{color:var(--ink)}}
.tabs{{display:flex;gap:8px;margin:4px 0 18px}}
.tab{{background:var(--panel);border:1px solid var(--line);color:var(--muted);border-radius:10px;
padding:8px 18px;font-size:13px;font-weight:600;cursor:pointer}}
.tab.active{{color:var(--ink);border-color:var(--accent);background:#18203a}}
.pane{{display:none}} .pane.active{{display:block}}
.cards{{display:grid;grid-template-columns:repeat(auto-fit,minmax(168px,1fr));gap:12px}}
.card{{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:14px 16px}}
.card .lbl{{color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.6px}}
.card .val{{font-size:24px;font-weight:650;margin-top:6px;letter-spacing:-.5px}}
.card .sub{{color:var(--muted);font-size:11px;margin-top:3px}}
.card.good .val{{color:var(--good)}} .card.bad .val{{color:var(--bad)}}
.card.warn .val{{color:var(--warn)}} .card.accent .val{{color:var(--accent)}}
table{{width:100%;border-collapse:collapse;background:var(--panel);
border:1px solid var(--line);border-radius:10px;overflow:hidden}}
th,td{{text-align:left;padding:7px 12px;border-bottom:1px solid var(--line);font-size:13px;vertical-align:top}}
th{{color:var(--muted);font-weight:600;font-size:11px;text-transform:uppercase;letter-spacing:.5px;background:#10141e}}
tr:last-child td{{border-bottom:none}}
.k{{color:var(--muted)}} .wrap{{max-width:420px}}
.good{{color:var(--good)}} .bad{{color:var(--bad)}} .muted{{color:var(--muted)}}
.pill{{display:inline-block;padding:1px 9px;border-radius:999px;font-size:11px;font-weight:700;
border:1px solid var(--line);background:#10141e}}
.pill.good{{color:var(--good)}} .pill.bad{{color:var(--bad)}} .pill.warn{{color:var(--warn)}}
.pill.muted{{color:var(--muted)}}
.empty{{color:var(--muted);font-size:13px;padding:8px 2px}}
.note{{color:var(--muted);font-size:11.5px;margin-top:8px;max-width:760px}}
ul.crits{{margin:4px 0;padding-left:20px;color:var(--bad);font-size:13px}}
ul.crits li{{margin:3px 0}}
.foot{{margin-top:34px;color:var(--muted);font-size:11px;border-top:1px solid var(--line);padding-top:12px}}
.grid2{{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:18px}}
</style>
</head>
<body>
<div class="head">
  <div><h1>🧭 Ops Dashboard</h1>
  <div class="asof">revenue efforts + system health · standalone (no server)</div></div>
  <div class="asof">generated <b>{_esc(now)}</b> · auto-refresh <span id="tick">{REFRESH_SECONDS}</span>s</div>
</div>

<div class="tabs">
  <button class="tab active" data-pane="rev">💰 Revenue</button>
  <button class="tab" data-pane="health">🩺 System Health</button>
</div>

<div id="rev" class="pane active">
  <section><h2>At a glance</h2><div class="cards">{hero}</div></section>
  <section><h2>Revenue lanes</h2>{lanes_tbl}</section>
  <section><h2>Costs · ROI · Savings</h2>{cost_tbl}<p class="note">{_esc(cost_note)}</p></section>
</div>

<div id="health" class="pane">
  <section><h2>launchd jobs</h2>{ld_html}</section>
  <section><h2>Key endpoints</h2>{ep_tbl}</section>
  <section><h2>Diagnostician</h2>{diag_html}</section>
  <section class="grid2"><div><h2>Spend breakers</h2>{br_tbl}</div>
  <div><h2>Disk &amp; runs</h2>{misc_tbl}</div></section>
</div>

<div class="foot">Sources: Stripe (read-only GETs) · tools/spend_dashboard · launchctl list ·
data/diagnostic_report.json · local port probes · guard state files. No secrets embedded.
Regenerated every 5 min by com.claude-stack.ops-dashboard; page re-reads itself every {REFRESH_SECONDS}s.</div>

<script>
document.querySelectorAll('.tab').forEach(function(t){{
  t.addEventListener('click', function(){{
    document.querySelectorAll('.tab').forEach(function(x){{x.classList.remove('active')}});
    document.querySelectorAll('.pane').forEach(function(x){{x.classList.remove('active')}});
    t.classList.add('active');
    document.getElementById(t.dataset.pane).classList.add('active');
  }});
}});
var n={REFRESH_SECONDS},el=document.getElementById('tick');
setInterval(function(){{n--;if(el)el.textContent=n>0?n:0;}},1000);
</script>
</body>
</html>
"""


def main(argv=None):
    argv = argv if argv is not None else sys.argv[1:]
    data = {}
    try:
        data["stripe"] = collect_stripe()
    except Exception as e:
        data["stripe"] = {"error": str(e)[:150]}
    try:
        data["lanes"] = collect_lanes(data["stripe"])
    except Exception:
        data["lanes"] = []
    data["spend"] = collect_spend()
    data["launchd"] = collect_launchd()
    data["endpoints"] = collect_endpoints()
    data["diag"] = collect_diag()
    data["breakers"] = collect_breakers()
    data["disk"] = collect_disk()
    data["smoke"] = collect_smoke()

    OUT_HTML.parent.mkdir(parents=True, exist_ok=True)
    OUT_HTML.write_text(build_html(data))
    if "--print" in argv:
        print(f"wrote {OUT_HTML}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
