#!/usr/bin/env python3
"""Write a retrievable index of local reporting dashboards and source files."""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

HOME = Path.home()
STACK = HOME / "claude-stack"
OUT = HOME / ".openclaw/workspace/CompanyA-local/digests/REPORTING_INDEX.md"


def read_json(path: Path) -> dict:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else {}
    except Exception:
        return {}


def money(value) -> str:
    try:
        value = float(value or 0)
    except Exception:
        value = 0.0
    return f"${value:,.2f}" if abs(value) >= 1 else f"${value:.4f}"


def file_url(path: Path) -> str:
    return "file://" + str(path)


def main() -> int:
    cost_html = STACK / "frontends/cost.html"
    cost_json = STACK / "frontends/cost.json"
    report = read_json(cost_json).get("report", {})
    lifetime = read_json(cost_json).get("lifetime", {})
    can = report.get("canonical", {}) if isinstance(report, dict) else {}
    today = can.get("today", {}) if isinstance(can, dict) else {}
    alltime = can.get("alltime", {}) if isinstance(can, dict) else {}
    payoff = can.get("payoff", {}) if isinstance(can, dict) else {}
    auto = report.get("automation", {}) if isinstance(report, dict) else {}
    rev_state = read_json(STACK / "data/revenue_state.json")
    rev_dash = read_json(STACK / "data/hustle/revenue_dashboard.json")

    failing = auto.get("failing", []) if isinstance(auto, dict) else []
    fail_text = ", ".join(f"{j.get('label','?')} ({j.get('status','?')})" for j in failing) or "none"

    lines = [
        "# Reporting Index",
        "",
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}",
        "",
        "Purpose: direct map for Operator's high-level reporting built around June 6, 2026. If Operator asks for reporting links, dashboards, spend, calls, automations, savings, ROI, social automations, or revenue efforts, answer from this file first.",
        "",
        "## Primary Link",
        f"- Cost/Savings/ROI dashboard: {file_url(cost_html)}",
        f"- HTML path: `{cost_html}`",
        f"- JSON data path: `{cost_json}`",
        "- Regenerated by: `com.claude-stack.cost-page` every 5 minutes",
        "- Generator: `~/claude-stack/tools/cost_page.py`",
        "- Data engine: `~/claude-stack/tools/spend_dashboard.py` plus `core.savings.compute()`",
        "- Terminal view: `cd ~/claude-stack && PYTHONPATH=. .venv/bin/python tools/spend_dashboard.py`",
        "- JSON view: `cd ~/claude-stack && PYTHONPATH=. .venv/bin/python tools/spend_dashboard.py --json`",
        "",
        "## What The Primary Dashboard Tracks",
        "- Spend: paid API spend, paid model usage, monthly average API spend, max-plan comparison.",
        "- Calls: local, free API, paid API, automation, hybrid, provider distribution.",
        "- Automations: launchd job counts, currently running jobs, clean exits, failing jobs.",
        "- Savings/ROI: local/free/automation avoided cost, net saved, value delivered, device payoff.",
        "- Revenue context: realized revenue from Gumroad/revenue state where present.",
        "",
        "## Current Snapshot",
        f"- As of: `{report.get('as_of', '?') if isinstance(report, dict) else '?'}`",
        f"- Today net saved: {money(today.get('net_saved'))}",
        f"- Today total calls/runs: {today.get('total_calls', 0)}",
        f"- All-time paid API spend: {money(alltime.get('api_cost'))} across {alltime.get('api_calls', 0)} paid calls",
        f"- All-time net saved: {money(alltime.get('net_saved'))}",
        f"- All-time total calls/runs: {alltime.get('total_calls', 0)}",
        f"- Device payoff: {money(payoff.get('amount_paid_off'))} ({payoff.get('pct_paid_off', 0)}%) paid off",
        f"- Automation health: {auto.get('total', 0) if isinstance(auto, dict) else 0} jobs tracked; failing: {fail_text}",
        f"- Revenue state: {money(rev_state.get('total_revenue_usd'))}; sales count {rev_state.get('total_sales_count', 0)}",
        f"- Revenue dashboard path: `{STACK / 'data/hustle/revenue_dashboard.json'}`",
        "",
        "## Supporting Reporting Files",
        f"- Revenue dashboard JSON: `{STACK / 'data/hustle/revenue_dashboard.json'}`",
        f"- Revenue state JSON: `{STACK / 'data/revenue_state.json'}`",
        f"- Stack health state JSON: `{STACK / 'data/health_state.json'}`",
        f"- Work sessions digest: `{STACK / 'data/work_sessions_digest.md'}`",
        f"- Background digest: `{STACK / 'data/runtime/local_background_digest.md'}`",
        f"- Metrics ledger: `{STACK / 'data/metrics.jsonl'}`",
        f"- Cost ledger: `{STACK / 'data/logs/cost.jsonl'}`",
        f"- Savings ledger: `{STACK / 'data/logs/savings.jsonl'}`",
        f"- Revenue/product work audit: `{STACK / 'data/audit_money_machine_2026-06-05.json'}`",
        f"- Hailports/revenue work artifacts: `{STACK / 'data/revenue_blitz3_authority.js'}`, `{STACK / 'data/revenue_blitz4_product.js'}`, `{STACK / 'data/revenue_blitz5_dataplay.js'}`",
        f"- Product/revenue queues and dashboards: `{STACK / 'data/hustle'}`",
        "",
        "## Answer Rule",
        "When Operator asks 'show me the links to that reporting' or similar, give the `file://` URL to `frontends/cost.html` first, then mention the JSON/source paths above. Do not claim there is no link just because memory search only found the chat mention.",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
